# ---------------------------------------------------------------------------------------
#  Your basic info
# ---------------------------------------------------------------------------------------
base_info:
  title: Allen Blog
  author: Allen Shih
  url: https://eepson123tw.github.io/
  # Logo image (You can use local image, image external link or don’t fill)
  logo_img: /images/logo/logo_transparent.png

# ---------------------------------------------------------------------------------------
# Theme style settings
# ---------------------------------------------------------------------------------------
style:
  # Theme primary color
  primary_color: "#9999CC"

  # Avatar (You can use local image or image external link)
  avatar: /images/avatar.svg

  # Favicon (You can use local image or image external link)
  favicon: /images/logo/favicon.png

  # Article image align position, value: left | center
  article_img_align: center

  # Left side width
  left_side_width: 260px

  # Content area max width
  content_max_width: 920px

  # Mouse hover
  hover:
    shadow: true # shadow effect when the mouse hover
    scale: true # scale effect when the mouse hover

  # First screen
  first_screen:
    enable: true
    background_img: /images/bg.svg # You can use local image or image external link
    description: 圍繞核心，漸進增強!

  # Scroll style settings
  scroll:
    progress_bar:
      enable: true
    percent:
      enable: true

# ---------------------------------------------------------------------------------------
# Social contact link
# ---------------------------------------------------------------------------------------
social_contact:
  enable: true
  links:
    github: https://github.com/eepson123tw # your GitHub URL
    weixin: # your WeChat QR-Code URL
    qq: # your QQ QR-Code URL
    weibo: # your WeiBo URL
    zhihu: # your ZhiHu URL
    twitter: # your twitter URL
    facebook: # your facebook URL
    email: eepson123tw@gmail.com # your email

# ---------------------------------------------------------------------------------------
# Navigation menu
# ---------------------------------------------------------------------------------------
menu:
  Home: /
  Archives: /archives
  Categories: /categories
  Tags: /tags
  # Links: /links
  About: /about
  # Changelog: /changelog
  # ......

# ---------------------------------------------------------------------------------------
# Home page article block display settings
# ---------------------------------------------------------------------------------------
home_article:
  category:
    enable: true # show category in home page article block
    limit: 3 # max number of categories shown in home page article block
  tag:
    enable: true # show tags in home page article block
    limit: 5 # max number of tags shown in home page article block

# ---------------------------------------------------------------------------------------
# Post page Settings
# ---------------------------------------------------------------------------------------
post:
  # Post word count
  # Dependencies: hexo-wordcount (npm install hexo-wordcount)
  # See: https://github.com/willin/hexo-wordcount
  word_count:
    enable: true
    wordcount: true # word count, one article
    min2read: true # time to read, one article

  # Author label
  author_label:
    enable: true
    auto: false # if true, show Lv1, Lv2, Lv3... , If false, show custom label
    # label array item can be one or more
    custom_label_list: ["前端工程師", "轉職打工仔"]

# ---------------------------------------------------------------------------------------
# Code copy
# ---------------------------------------------------------------------------------------
code_copy:
  enable: false
  style: default # values: default | mac

# ---------------------------------------------------------------------------------------
# Table of Contents in the Sidebar
# ---------------------------------------------------------------------------------------
toc:
  enable: true
  # Automatically add list number to toc.
  number: true
  # If true, all level of TOC in a post will be displayed, rather than the activated part of it.
  expand_all: false
  # If true, open TOC every time when you enter the article page
# ---------------------------------------------------------------------------------------
# Post copyright info
# ---------------------------------------------------------------------------------------
copyright_info:
  enable: false

# ---------------------------------------------------------------------------------------
# Website count
# ---------------------------------------------------------------------------------------
website_count:
  # busuanzi
  # See: http://ibruce.info/2015/04/04/busuanzi/
  busuanzi_count:
    enable: true
    site_uv: true
    site_pv: true
    page_pv: true

# ---------------------------------------------------------------------------------------
# Local Search
# Dependencies: hexo-generator-searchdb
# See: https://github.com/theme-next/hexo-generator-searchdb
# ---------------------------------------------------------------------------------------
local_search:
  enable: true
  preload: false # Preload the search data when the page loads

# ---------------------------------------------------------------------------------------
# RSS
# Dependencies: hexo-generator-feed
# See: https://github.com/hexojs/hexo-generator-feed
# ---------------------------------------------------------------------------------------
rss:
  enable: false

# ---------------------------------------------------------------------------------------
# Lazyload image
# ---------------------------------------------------------------------------------------
lazyload:
  enable: true

# ---------------------------------------------------------------------------------------
# CDN
# ---------------------------------------------------------------------------------------
cdn:
  enable: false

# ---------------------------------------------------------------------------------------
# PJAX
# ---------------------------------------------------------------------------------------
pjax:
  enable: false

# Google Analytics
google_analytics: "{G-R6YQL587WJ}"
# google_analytics:
#   tracking_id: G-R6YQL587WJ
#   localhost_ignored: true

# ---------------------------------------------------------------------------------------
# Footer settings
# ---------------------------------------------------------------------------------------
footer:
  since: 2021 # the starting year of your website, Can be null
  icp: # ICP record number of your website, Can be null
  upyun: # url

# Search
## See: https://github.com/theme-next/hexo-generator-searchdb
search:
  path: search.json
  field: post
  content: true
  format: striptags

post_asset_folder: true
marked:
  prependRoot: true
  postAsset: true
# ---------------------------------------------------------------------------------------
# Comment plugin
# ---------------------------------------------------------------------------------------

comment:
  enable: true
  use: gitalk # values: valine | gitalk | twikoo

  # Gitalk
  # See: https://github.com/gitalk/gitalk
  gitalk:
    github_id: eepson123tw # GitHub repo owner
    repository: eepson123tw.gitalk # Repository name to store issues
    client_id: b57e764afef07bde3085 # GitHub Application Client ID
    client_secret: 7b8d5b15886c8be0aaaac7fe3945bd94a6aff797 # GitHub Application Client Secret
    owner: eepson123tw
    admin: [eepson123tw]
# ---------------------------------------------------------------------------------------
# Keep version (Please don't modify)
# ---------------------------------------------------------------------------------------



# ## ======================================================================================
# ## Keep v3.5.2
# ## Preview: https://xpoet.cn
# ## Document: https://keep-docs.xpoet.cn
# ## Repository: https://github.com/XPoet/hexo-theme-keep
# ## ======================================================================================

# # ---------------------------------------------------------------------------------------
# #  Your basic info
# # ---------------------------------------------------------------------------------------
# base_info:
#   # Your blog website title
#   title: Keep Theme

#   # Your blog website author name
#   author: Keep Team

# # ---------------------------------------------------------------------------------------
# # Theme style settings
# # ---------------------------------------------------------------------------------------
# style:
#   # Theme primary color
#   primary_color: "#0066cc"

#   # Your blog website logo image
#   # You can use local image, image external link or don’t fill
#   logo: /images/logo.svg

#   # Favicon (You can use local image or image external link)
#   favicon: /images/logo.svg

#   # Avatar (You can use local image or image external link)
#   avatar: /images/avatar.svg

#   # Font size, customize font size. (you don't usually have to fill)
#   # e.g. font_size: 18px
#   font_size:

#   # Font family, customize font family. (you don't usually have to fill)
#   # e.g. font_family: STKaiti, STSong, STHeiti
#   font_family:

#   # Mouse hover style settings
#   hover:
#     # Shadow effect when the mouse hover.
#     shadow: false  # Option values: true | false
#     # Scale effect when the mouse hovers.
#     scale: false   # Option values: true | false

#   # First screen style settings
#   first_screen:
#     enable: false  # Option values: true | false

#     # Set transparent background for header.
#     header_transparent: false  # Option values: true | false

#     # First screen background image (You can use local image or image external link)
#     background_img: /images/bg.svg

#     # First screen description
#     # You can use the "||" to begin a newline, maximum is two lines.
#     description: Keep writing and Keep loving.

#     # If you want to customize the first screen font color, you can fill in here (e.g. "#0066CC")
#     # Otherwise use the theme default font color
#     font_color:

#     # If enable hitokoto, first screen description is different every time when you enter the site
#     hitokoto: false  # Option values: true | false

#   # Page scroll style settings
#   scroll:
#     # Show progress bar in top when page scroll
#     progress_bar: false # Option values: true | false

#     # Show percent when page scroll
#     percent: false      # Option values: true | false

# # ---------------------------------------------------------------------------------------
# # Navigation menu
# # ---------------------------------------------------------------------------------------
# # If you want to enable Categories and Tags, you need to create categories and tags pages
# # e.g. `hexo new page categories` or `hexo new page tags`
# menu:
#   Home: /
#   Archives: /archives
#   # Tags: /tags
#   # Categories: /categories
#   # Links: /links
#   # About: /about
#   # Changelog: /changelog
#   # ......

# # ---------------------------------------------------------------------------------------
# # Social contact link
# # ---------------------------------------------------------------------------------------
# social_contact:
#   enable: false      # Option values: true | false
#   links:
#     # Fill in your social platform links here, e.g. [ github: https://github.com/XPoet ]
#     # If you want to click open the picture, you need to add a prefix "img |",
#     # at the same time change your link to the image link.
#     # e.g. [ weixin: img | https://x.com/images/wechat.png ] or [ weixin: img | ./images/wechat.png ]
#     github:          # GitHub
#     weixin:          # WeChat
#     qq:              # QQ
#     weibo:           # WeiBo
#     zhihu:           # ZhiHu
#     twitter:         # Twitter
#     facebook:        # Facebook
#     email:           # Email

# # ---------------------------------------------------------------------------------------
# # Home page article block display settings
# # ---------------------------------------------------------------------------------------
# home_article:
#   # Show category in home page article block.
#   category:
#     enable: false  # Option values: true | false
#     limit: 3       # Max number of categories shown in home page article block
#   # Show tags in home page article block.
#   tag:
#     enable: false  # Option values: true | false
#     limit: 5       # Max number of tags shown in home page article block

# # ---------------------------------------------------------------------------------------
# # Post page Settings
# # ---------------------------------------------------------------------------------------
# post:
#   # Author label in the post
#   author_label:
#     enable: true  # Option values: true | false

#     # If true, show Lv1, Lv2, Lv3...
#     # If false, show custom_label_list
#     auto: true    # Option values: true | false

#     # Label array item can be fill one or more
#     custom_label_list: ["Trainee", "Engineer", "Architect"]

#   # Post word count
#   # Dependencies: hexo-wordcount (`npm install hexo-wordcount`)
#   # See: https://github.com/willin/hexo-wordcount
#   word_count:
#     enable: false       # Option values: true | false
#     wordcount: false    # Word count, one article. Option values: true | false
#     min2read: false     # Time to read, one article. Option values: true | false

#   # Image align position in the post
#   img_align: left  # Option values: left | center

#   # Post copyright info
#   copyright_info: false  # Option values: true | false

# # ---------------------------------------------------------------------------------------
# # Code block
# # ---------------------------------------------------------------------------------------
# code_block:
#   # Toolbar include: "code copy", "code block collapse" and "code language"
#   tools:
#     enable: false            # Option values: true | false
#     style: default           # Option values: default | mac
#   highlight_theme: default   # Option values: default | obsidian

# # ---------------------------------------------------------------------------------------
# # Table of Contents in the Sidebar
# # ---------------------------------------------------------------------------------------
# toc:
#   enable: false      # Option values: true | false

#   # Automatically add list number to toc.
#   number: false      # Option values: true | false

#   # If true, all level of TOC in a post will be displayed, rather than the activated part of it.
#   expand_all: false  # Option values: true | false

#   # If true, open TOC every time when you enter the article page
#   init_open: false   # Option values: true | false

# # ---------------------------------------------------------------------------------------
# # Website count
# # ---------------------------------------------------------------------------------------
# website_count:
#   # busuanzi
#   # See: http://ibruce.info/2015/04/04/busuanzi/
#   busuanzi_count:
#     enable: false     # Option values: true | false
#     site_uv: false    # Option values: true | false
#     site_pv: false    # Option values: true | false
#     page_pv: false    # Option values: true | false

# # ---------------------------------------------------------------------------------------
# # Local Search
# # Dependencies: hexo-generator-searchdb (`npm install hexo-generator-searchdb`)
# # See: https://github.com/theme-next/hexo-generator-searchdb
# # ---------------------------------------------------------------------------------------
# local_search:
#   enable: false   # Option values: true | false
#   preload: false  # Preload the search data when the page loads. Option values: true | false

# # ---------------------------------------------------------------------------------------
# # Comment plugin
# # ---------------------------------------------------------------------------------------
# comment:
#   enable: false   # Option values: true | false
#   use: valine     # Option values: valine | gitalk | twikoo | waline

#   # Valine
#   # See: https://github.com/xCss/Valine
#   #      https://valine.js.org
#   valine:
#     appid:           # Your leancloud application appid
#     appkey:          # Your leancloud application appkey
#     placeholder:     # Input box placeholder

#   # Gitalk
#   # See: https://github.com/gitalk/gitalk
#   #      https://gitalk.github.io
#   gitalk:
#     github_id:        # GitHub repo owner
#     github_admins:    # GitHub Admins (in Array type), optional.
#     repository:       # Repository name to store issues
#     client_id:        # GitHub Application Client ID
#     client_secret:    # GitHub Application Client Secret

#   # Twikoo
#   # See: https://github.com/imaegoo/twikoo
#   #      https://twikoo.js.org
#   twikoo:
#     env_id:         # Tencent Cloud environment id
#     region:         # Environment region. If select Guangzhou, fill in "ap-guangzhou".
#     version: 1.6.7  # Twikoo version, default use v1.6.7

#   # Waline
#   # See: https://github.com/walinejs/waline
#   #      https://waline.js.org/guide/get-started.html
#   waline:
#     server_url:     # Server URL
#     reaction: false # Article reactions, Option values: true | false
#     version: 2      # Waline version, default use v2

# # ---------------------------------------------------------------------------------------
# # RSS
# # Dependencies: hexo-generator-feed
# # See: https://github.com/hexojs/hexo-generator-feed
# # ---------------------------------------------------------------------------------------
# rss:
#   enable: false  # Option values: true | false

# # ---------------------------------------------------------------------------------------
# # Lazyload image
# # ---------------------------------------------------------------------------------------
# lazyload:
#   enable: false  # Option values: true | false

# # ---------------------------------------------------------------------------------------
# # CDN
# # ---------------------------------------------------------------------------------------
# cdn:
#   enable: false       # Option values: true | false
#   provider: jsdelivr  # Option values: jsdelivr | unpkg

# # ---------------------------------------------------------------------------------------
# # PJAX
# # ---------------------------------------------------------------------------------------
# pjax:
#   enable: false  # Option values: true | false

# # ---------------------------------------------------------------------------------------
# # Footer settings
# # ---------------------------------------------------------------------------------------
# footer:
#   since: 2020  # the starting year of your website. Can be null
#   icp:         # ICP record number of your website. Can be null
#   upyun:       # If your site is deployed on upyun, your can fill the upyun url. Can be null
