# 配置檔名稱
name: Deploy
# 進行什麼行為時觸發，也可多行為觸發，例如[push, fork]
on: [push]

jobs:
  pages:
    # 環境提供作業系統，目前提供Windows, macOS, Ubuntu，詳細查閱（https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#choosing-github-hosted-runners）
    runs-on: ubuntu-latest
    steps:
      # 拉取當前Repository的分支main的Code到他們的容器（如配置檔中使用的Runs-on的Ubuntu）上
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: main

      # 安裝Nodejs環境
      - name: Use Node.js 14.15.1
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      # 緩存
      - name: Cache NPM Dependencies
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.OS }}-npm-cache
          restore-keys: |
            ${{ runner.OS }}-npm-cache

      # 增加SSH KEY的配置
      - name: Add SSH Private Key
        env:
          SSH_PRIVATE: ${{ secrets.HEXO_SSH_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_PRIVATE" > ~/.ssh/id_rsa
          chmod 700 -R ~/.ssh
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          git config --global user.email "eepson123@gmail.com"
          git config --global user.name "eepson123tw"

      # 安裝Hexo需要的環境（針對Hexo根目錄的package.json）ts
      - name: Install Dependencies
        run: |
          npm install hexo-cli -g
          npm install

      # 一鍵化部署
      - name: Hexo Deploy
        run: |
          hexo clean
          hexo d -g
